security:
    access_decision_manager:
        strategy: unanimous
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512
    role_hierarchy:
        ROLE_RITSIGA_ORGANIZER_ritsi:
            - ROLE_ritsi_RITSIGA_ADMIN_CONVENTION_CREATE
            - ROLE_ritsi_RITSIGA_ADMIN_CONVENTION_DELETE
            - ROLE_ritsi_RITSIGA_ADMIN_CONVENTION_EDIT
            - ROLE_ritsi_RITSIGA_ADMIN_CONVENTION_LIST
            - ROLE_ritsi_RITSIGA_ADMIN_CONVENTION_VIEW
            - ROLE_ritsi_RITSIGA_ADMIN_COLLEGE_CREATE
            - ROLE_ritsi_RITSIGA_ADMIN_COLLEGE_DELETE
            - ROLE_ritsi_RITSIGA_ADMIN_COLLEGE_EDIT
            - ROLE_ritsi_RITSIGA_ADMIN_COLLEGE_EXPORT
            - ROLE_ritsi_RITSIGA_ADMIN_COLLEGE_LIST
            - ROLE_ritsi_RITSIGA_ADMIN_COLLEGE_VIEW
            - ROLE_ritsi_RITSIGA_ADMIN_STUDENTDELEGATION_CREATE
            - ROLE_ritsi_RITSIGA_ADMIN_STUDENTDELEGATION_DELETE
            - ROLE_ritsi_RITSIGA_ADMIN_STUDENTDELEGATION_EDIT
            - ROLE_ritsi_RITSIGA_ADMIN_STUDENTDELEGATION_EXPORT
            - ROLE_ritsi_RITSIGA_ADMIN_STUDENTDELEGATION_LIST
            - ROLE_ritsi_RITSIGA_ADMIN_STUDENTDELEGATION_VIEW
            - ROLE_ritsi_RITSIGA_ADMIN_UNIVERSITY_CREATE
            - ROLE_ritsi_RITSIGA_ADMIN_UNIVERSITY_DELETE
            - ROLE_ritsi_RITSIGA_ADMIN_UNIVERSITY_EDIT
            - ROLE_ritsi_RITSIGA_ADMIN_UNIVERSITY_EXPORT
            - ROLE_ritsi_RITSIGA_ADMIN_UNIVERSITY_LIST
            - ROLE_ritsi_RITSIGA_ADMIN_UNIVERSITY_VIEW
            - ROLE_RITSI_SONATA_USER_ADMIN_USER_CREATE
            - ROLE_RITSI_SONATA_USER_ADMIN_USER_DELETE
            - ROLE_RITSI_SONATA_USER_ADMIN_USER_EDIT
            - ROLE_RITSI_SONATA_USER_ADMIN_USER_EXPORT
            - ROLE_RITSI_SONATA_USER_ADMIN_USER_LIST
            - ROLE_RITSI_SONATA_USER_ADMIN_USER_VIEW
        ROLE_RITSIGA_ORGANIZER_CONVENTION:
            - ROLE_RITSI_RITSIGA_ADMIN_CONVENTION_LIST
            - ROLE_RITSI_RITSIGA_ADMIN_CONVENTION_VIEW
            - ROLE_RITSI_RITSIGA_ADMIN_CONVENTION_EDIT
            - ROLE_RITSI_RITSIGA_ADMIN_REGISTRATION_LIST
            - ROLE_RITSI_RITSIGA_ADMIN_REGISTRATION_CREATE
            - ROLE_RITSI_RITSIGA_ADMIN_REGISTRATION_VIEW
            - ROLE_RITSI_RITSIGA_ADMIN_REGISTRATION_EDIT
            - ROLE_RITSI_RITSIGA_ADMIN_REGISTRATION_DELETE
            - ROLE_RITSI_RITSIGA_ADMIN_REGISTRATION_EXPORT
            - ROLE_RITSI_RITSIGA_ADMIN_PARTICIPANT_LIST
            - ROLE_RITSI_RITSIGA_ADMIN_PARTICIPANT_CREATE
            - ROLE_RITSI_RITSIGA_ADMIN_PARTICIPANT_VIEW
            - ROLE_RITSI_RITSIGA_ADMIN_PARTICIPANT_EDIT
            - ROLE_RITSI_RITSIGA_ADMIN_PARTICIPANT_DELETE
            - ROLE_RITSI_RITSIGA_ADMIN_PARTICIPANT_EXPORT
            - ROLE_RITSI_RITSIGA_ADMIN_TICKET_LIST
            - ROLE_RITSI_RITSIGA_ADMIN_TICKET_CREATE
            - ROLE_RITSI_RITSIGA_ADMIN_TICKET_VIEW
            - ROLE_RITSI_RITSIGA_ADMIN_TICKET_EDIT
            - ROLE_RITSI_RITSIGA_ADMIN_TICKET_DELETE
            - ROLE_RITSI_RITSIGA_ADMIN_UNIVERSITY_LIST
            - ROLE_RITSI_RITSIGA_ADMIN_UNIVERSITY_VIEW
            - ROLE_RITSI_RITSIGA_ADMIN_UNIVERSITY_EDIT
            - ROLE_RITSI_RITSIGA_ADMIN_UNIVERSITY_EXPORT
            - ROLE_RITSI_RITSIGA_ADMIN_COLLEGE_LIST
            - ROLE_RITSI_RITSIGA_ADMIN_COLLEGE_VIEW
            - ROLE_RITSI_RITSIGA_ADMIN_COLLEGE_EDIT
            - ROLE_RITSI_RITSIGA_ADMIN_COLLEGE_EXPORT
            - ROLE_RITSI_RITSIGA_ADMIN_STUDENTDELEGATION_LIST
            - ROLE_RITSI_RITSIGA_ADMIN_STUDENTDELEGATION_VIEW
            - ROLE_RITSI_RITSIGA_ADMIN_STUDENTDELEGATION_EDIT
            - ROLE_RITSI_RITSIGA_ADMIN_STUDENTDELEGATION_EXPORT
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_RITSIGA_ORGANIZER_ritsi]
        ROLE_ORGANIZER:   [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # default login area for standard users

        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle
        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                default_target_path:     /
                failure_path:   null
            oauth:
                resource_owners:
                    google:             "/login/check-google"
                    sir:                "/login/check-sir"
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: my_user_provider
            logout:       true
            anonymous:    true

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/convention/[\w\d]+/admin/, role: [ROLE_SONATA_ADMIN] }
        - { path: ^/convention/[\w\d]+/.*/, role: [ROLE_USER] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }