# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#       class: AppBundle\Directory\ClassName
#       arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    ritsiga.site.manager:
        class: AppBundle\Site\SiteManager

    ritsiga.listener.site:
        class: AppBundle\EventListener\CurrentSiteListener
        arguments:
           - "@ritsiga.site.manager"
           - "@doctrine.orm.default_entity_manager"
           - "@router"
           - "%base_code%"
        tags:
           -
              name: kernel.event_listener
              method: onKernelRequest
              event: kernel.request
              priority: 1

    ritsiga.listener.maintenance:
        class: AppBundle\EventListener\MaintenanceListener
        arguments:
           - "@ritsiga.site.manager"
           - "@service_container"
        tags:
           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 5 }

    ritsiga.listener.notification:
        class: AppBundle\EventListener\NotificationListener
        arguments:
           - "@service_container"
        tags:
           - { name: kernel.event_subscriber }
           - { name: doctrine.event_listener, event: preUpdate }

    sylius.scenario.flow:
        class: AppBundle\Process\SyliusScenario
        calls:
           - [ setContainer, [ @service_container ] ]
        tags:
           -
              name: sylius.process.scenario
              alias: asamblea

    my_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        arguments: [ @fos_user.user_manager, { google: google_id, sir: sir_id } ]

##### LÓGICA DE NEGOCIO

    ritsiga.business.document_generator:
        class: AppBundle\Business\DocumentGenerator
        arguments: [ @knp_snappy.pdf, @twig ]

##### SONATA ADMIN ######

    ritsiGA.admin.convention:
        class: AppBundle\Admin\ConventionAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "Asambleas", label: "Asambleas" }
        arguments:
           - ~
           - AppBundle\Entity\Convention
           - AppBundle:Backend\ConventionCRUD

    ritsiGA.admin.ticket:
        class: AppBundle\Admin\TicketAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "Asambleas", label: label.ticket }
        arguments:
           - ~
           - AppBundle\Entity\Ticket
           - ~

    ritsiGA.admin.registration:
        class: AppBundle\Admin\RegistrationAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "Asambleas", label: "Inscripciones" }
        arguments:
           - ~
           - AppBundle\Entity\Registration
           - ~
        calls:
            - [ setTemplate, [inner_list_row, backend/Registration/CRUD/inner_list_row.html.twig]]
            - [ setTemplate, [base_list_field, SonataAdminBundle:CRUD:base_list_flat_field.html.twig]]

    ritsiGA.admin.participant:
        class: AppBundle\Admin\ParticipantAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "Asambleas", label: "Participantes" }
        arguments:
           - ~
           - AppBundle\Entity\Participant
           - ~

    ritsiGA.admin.university:
        class: AppBundle\Admin\UniversityAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "Universidades" }
        arguments:
           - ~
           - AppBundle\Entity\University
           - ~

    ritsiGA.admin.college:
        class: AppBundle\Admin\CollegeAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "Facultades" }
        arguments:
           - ~
           - AppBundle\Entity\College
           - ~

    ritsiGA.admin.studentdelegation:
        class: AppBundle\Admin\StudentDelegationAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "Delegaciones de Estudiantes" }
        arguments:
           - ~
           - AppBundle\Entity\StudentDelegation
           - ~

    sonata.user.admin.group:
        abstract: true
        public: false

## FORMULARIOS ###

    ritsiga.profile.form.type:
        class: AppBundle\Form\Type\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
           - { name: form.type, alias: ritsiga_user_profile }

    ritsiga.participant.form.type:
        class: AppBundle\Form\ParticipantType
        arguments: [@ritsiga.site.manager, @ritsiga.repository.ticket]
        tags:
           - { name: form.type, alias: participant }

    ritsiga.registration.form.type:
        class: AppBundle\Form\RegistrationType
        arguments: [@ritsiga.participant.form.type]
        tags:
           - { name: form.type, alias: registration }

    ritsiga.profile.form.handler:
        class: AppBundle\Form\Type\ProfileFormHandler
        arguments: [@fos_user.profile.form, @request, @fos_user.user_manager]
        scope: request
        public: false

    ritsiga.form_type.tax_data_type:
        class: AppBundle\Form\Type\TaxDataType
        tags:
            - { name: form.type, alias: taxdata }

## REPOSITORY
    ritsiga.repository.convention:
        class: AppBundle\Doctrine\ORM\ConventionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Convention']

    ritsiga.repository.ticket:
        class: AppBundle\Doctrine\ORM\TicketRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Ticket']

    ritsiga.repository.registration:
        class: AppBundle\Doctrine\ORM\RegistrationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\Registration']

    ritsiga.repository.college:
        class: AppBundle\Doctrine\ORM\CollegeRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\College']

    ritsiga.repository.student_delegation:
        class: AppBundle\Doctrine\ORM\StudentDelegationRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ['AppBundle\Entity\StudentDelegation']

## TWIG

    ritsiGA.twig.conventionextension:
        class: AppBundle\Twig\ConventionExtension
        arguments: [ @request_stack, @ritsiga.site.manager ]
        public: false
        tags:
           - { name: twig.extension }

## HANDLER

    ritsiGA.security.handler.convention:
        class: AppBundle\Security\Handler\RoleConventionSecurityHandler
        arguments: [@security.authorization_checker, ['ROLE_SUPER_ADMIN'], @ritsiga.site.manager]

    security.role_hierarchy:
        class: AppBundle\Security\Core\Role\RoleHierarchy
        public: false
        arguments: [ %security.role_hierarchy.roles%, @doctrine.orm.entity_manager ]

## VOTERS

    ritsiGA.security_voter.convention_voter:
        class: AppBundle\Security\Voter\Sonata\ConventionVoter
        arguments: [@ritsiga.site.manager, @security.role_hierarchy]
        tags:
           - { name: security.voter }

    ritsiGA.security_voter.participantype_voter:
        class: AppBundle\Security\Voter\Sonata\TicketVoter
        arguments: [@ritsiga.site.manager, @security.role_hierarchy]
        tags:
           - { name: security.voter }

    ritsiGA.security_voter.participant_voter:
        class: AppBundle\Security\Voter\Sonata\ParticipantVoter
        arguments: [@ritsiga.site.manager, @security.role_hierarchy]
        tags:
           - { name: security.voter }

    ritsiGA.security_voter.registration_voter:
        class: AppBundle\Security\Voter\Sonata\RegistrationVoter
        arguments: [@ritsiga.site.manager, @security.role_hierarchy]
        tags:
           - { name: security.voter }

    ritsiGA.security_voter.available_seats_voter:
        class: AppBundle\Security\Voter\AvailableSeatsVoter
        arguments: [ @ritsiga.repository.convention ]
        tags:
            - { name: security.voter }

    ritsiGA.security_voter.registration_owner_voter:
        class: AppBundle\Security\Voter\RegistrationOwnerVoter
        tags:
            - { name: security.voter }

    ritsiga.security_voter.invoice_voter:
        class: AppBundle\Security\Voter\InvoiceVoter
        tags:
            - { name: security.voter }

#    ritsiGA.security_voter.organizer_voter:
#        class: AppBundle\Security\Voter\Sonata\AdminVoter
#        arguments: [ @ritsiga.site.manager, @security.role_hierarchy ]
#        tags:
#          - { name: security.voter }