# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     ritsiga.site.manager:
         class: AppBundle\Site\SiteManager

     ritsiga.site.listener:
         class: AppBundle\EventListener\CurrentSiteListener
         arguments:
             - "@ritsiga.site.manager"
             - "@doctrine.orm.default_entity_manager"
             - "%base_host%"
             - "@kernel"
         tags:
             -
                 name: kernel.event_listener
                 method: onKernelRequest
                 event: kernel.request


     sylius.scenario.flow:
         class: AppBundle\Process\SyliusScenario
         calls:
             - [ setContainer, [ @service_container ] ]
         tags:
             -
                 name: sylius.process.scenario
                 alias: asamblea

     my_user_provider:
         class: AppBundle\Security\Core\User\FOSUBUserProvider
         #this is the place where the properties are passed to the UserProvider - see config.yml
         arguments: [@fos_user.user_manager,{google: google_id}]

##### SONATA ADMIN ######

     ritsiGA.admin.convention:
         class: AppBundle\Admin\ConventionAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, group: "Asambleas", label: "Conventions" }
         arguments:
             - ~
             - AppBundle\Entity\Convention
             - ~

     ritsiGA.admin.university:
         class: AppBundle\Admin\UniversityAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "Universities" }
         arguments:
             - ~
             - AppBundle\Entity\University
             - ~

     ritsiGA.admin.college:
         class: AppBundle\Admin\CollegeAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "Colleges" }
         arguments:
             - ~
             - AppBundle\Entity\College
             - ~

     ritsiGA.admin.studentdelegation:
         class: AppBundle\Admin\StudentDelegationAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, group: "Entidades", label: "Students Delegations" }
         arguments:
             - ~
             - AppBundle\Entity\StudentDelegation
             - ~
